### ISSUE TITLE
Implement configuration file support for unattended installs

### ISSUE THREAD

**Issue by amin3141** [PAIR-Systems-Inc/goodmem#60]
# Implement configuration file support for unattended installs

## Problem Statement

The current installer supports some unattended installation via command-line flags (`--prod-install`, `--debug-install`, `--no-openai-embedder-registration`), but this approach doesn't scale well for complex configurations. For enterprise deployments and CI/CD scenarios, a configuration file approach would be more maintainable and user-friendly.

## Current Limitations

1. **Database Configuration**: PostgreSQL username, password, and database name are hardcoded with basic environment variable fallbacks
2. **Limited Scalability**: Adding new configuration options requires new command-line flags
3. **Data Directory**: Database data directory is fixed to `$GOODMEM_DIR/data/pgdata`
4. **No Persistence**: Configuration choices aren't saved for future reference or updates

## Proposed Solution

Implement support for configuration files (preferably TOML format, with .env as fallback) that the installer can read to determine installation parameters.

### Configuration File Format (goodmem-config.toml)

```toml
[installation]
mode = "prod"  # or "debug"
goodmem_dir = "/opt/goodmem"  # default: ~/.goodmem
cli_install_dir = "/usr/local/bin"  # default: /usr/local/bin

[database]
username = "custom_user"
password = "secure_password"
database_name = "custom_db"
data_directory = "/data/postgresql"  # external mount point

[embedder]
# Options: "openai", "tei", "none"
provider = "openai"

[embedder.openai]
api_key = "sk-..."
model = "text-embedding-3-small"

[embedder.tei]
model = "sentence-transformers/all-MiniLM-L6-v2"
use_gpu = true
max_batch_requests = 512
max_concurrent_requests = 128
```

### Environment File Alternative (.env)

```bash
# Installation settings
GOODMEM_INSTALL_MODE=prod
GOODMEM_DIR=/opt/goodmem
CLI_INSTALL_DIR=/usr/local/bin

# Database settings
POSTGRES_USER=custom_user
POSTGRES_PASSWORD=secure_password
POSTGRES_DB=custom_db
POSTGRES_DATA_DIR=/data/postgresql

# Embedder settings
EMBEDDER_PROVIDER=openai
OPENAI_API_KEY=sk-...
```

### 1. Configuration File Detection
- Check for `goodmem-config.toml` in current directory
- Fallback to `.env` file if TOML not found
- Support specifying config file path via `--config` flag
- Maintain backward compatibility with existing flags

### 2. TOML Parsing
Since the installer is bash-based, consider:
- Using `yq` for TOML parsing (if available)
- Implementing simple bash-based TOML parser for basic use cases
- Providing clear error messages for malformed config files

### 3. Configuration Precedence
1. Command-line flags (highest priority)
2. Configuration file values
3. Environment variables
4. Interactive prompts (lowest priority)

### 4. Database Configuration Externalization
- Support custom PostgreSQL credentials
- Allow external data directory specification
- Update docker-compose.yml generation to use custom values
- Ensure proper volume mounting for external directories

### 5. Validation and Error Handling
- Validate configuration file syntax
- Check for required fields based on chosen options
- Provide clear error messages for invalid configurations
- Support config file validation without installation (`--validate-config`)

## Acceptance Criteria

- [ ] Support TOML configuration file format
- [ ] Fallback to .env file format
- [ ] Implement configuration precedence (CLI > config file > env > interactive)
- [ ] Add `--config` flag to specify custom config file path
- [ ] Support external PostgreSQL data directory
- [ ] Allow custom database credentials
- [ ] Add `--validate-config` flag for config validation
- [ ] Maintain backward compatibility with existing flags
- [ ] Update docker-compose.yml generation for custom values
- [ ] Add comprehensive error handling for config files
- [ ] Document configuration file format and options

## Example Usage

```bash
# Using TOML config file
./install.sh --config ./production.toml

# Using .env file (auto-detected)
./install.sh

# Validation only
./install.sh --validate-config --config ./test-config.toml

# Override config file setting via CLI
./install.sh --config ./base.toml --prod-install
```

## Benefits

1. **Scalability**: Easy to add new configuration options
2. **Maintainability**: Configuration can be version-controlled
3. **Reusability**: Same config can be used across environments
4. **Documentation**: Config file serves as documentation
5. **Validation**: Can validate configuration before installation
6. **CI/CD Friendly**: Perfect for automated deployments

## Related Files

- `installer/install.sh` (entire file, especially argument parsing and environment variable handling)
- `installer/docker-compose.yml` (template that needs to be more configurable)

## Future Enhancements

- Configuration file generation wizard
- Multi-environment configuration support
- Configuration file encryption for sensitive values
- Integration with secrets management systems

## Parent Issue

Part of #56 - Installer Improvements: Enhanced Configuration and User Experience
